server.port=8080
spring.application.name=main-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/ewm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ewm_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ewm_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

management.endpoints.web.exposure.include=health,info

spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

stats-server.url=${STATS_SERVER_URL:http://localhost:9090}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=UTC